In [470]:
import numpy as np#function to find maximum coins in matrix by robot

def MaxCoin(r,c,CoinMatrix):    #2d matrix with rows=r+1 and columns=c+1 
    final_array=[[0]*(c+1) for _ in range(r+1)]

    #iterate through rows
    for i in range(1, r+1):        #iterate through columns    
        for j in range(1, c+1):          #find maximum number in 2d matrix and add 1 if the cell containing a coin 
            # print(final_array[i][j])
            # print(i,j)
            try:
                final_array[i][j] = max(final_array[i-1][j], final_array[i][j-1], final_array[i+1][j-1]) + CoinMatrix[i-1][j-1]
            except:
                final_array[i][j] = max(final_array[i-1][j], final_array[i][j-1]) + CoinMatrix[i-1][j-1]


    #print path
    print('Coins collected by Robot at each level are:', ',\n', np.flip(np.matrix(final_array), 1))    #print Maximum coin collected by robot
    print('Maximum Coins collected by Robot are: ',final_array[r][c])

In [471]:
CoinMatrix=[[1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
            [0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
            [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
            [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
            [1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0],
            [0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
            [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
            [1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]]

print("Input Matrix: \n", np.matrix(CoinMatrix))

CoinMatrix = np.flip(np.matrix(CoinMatrix), 1).tolist()

Input Matrix: 
 [[1 1 0 1 0 0 0 1 1 0 1 1 1 0 0 1]
 [0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0]
 [0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]]


In [472]:
rows = 8
col = 16

In [473]:
MaxCoin(rows,col,CoinMatrix) #call MaxCoin function with given parameters

Coins collected by Robot at each level are: ,
 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 9  8  7  7  6  6  6  6  5  4  4  3  2  1  1  1  0]
 [10 10  9  8  8  7  7  6  6  5  4  3  3  2  2  1  0]
 [11 10 10  9  9  8  8  7  7  5  5  4  4  3  3  1  0]
 [11 11 10 10  9  9  8  8  7  6  5  5  4  4  3  2  0]
 [13 12 11 10 10 10 10  9  8  6  6  6  6  5  4  2  0]
 [13 13 12 12 12 12 11 10  9  9  8  7  6  5  4  3  0]
 [14 14 14 13 12 12 12 11  9  9  9  8  6  5  5  4  0]
 [16 15 14 14 14 13 12 11 11 10  9  8  7  6  5  4  0]]
Maximum Coins collected by Robot are:  16
